displayName=Extended Ignore List
author=MichaelLavin778
description=Extend your ignore list limit
tags=ignore,list,social,chat
version=1.0.0
plugins=com.extendedignorelist.ExtendedIgnoreListPlugin
build=standard
